<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jDcfv45' shared service.

return $this->privates['.service_locator.jDcfv45'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::alimenterCompte' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\DepotController::depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController::newPartenaire' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UserController::newUser' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\CompteController:alimenterCompte' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
    'App\\Controller\\DepotController:depot' => ['privates', '.service_locator.7zWnKy7', 'get_ServiceLocator_7zWnKy7Service.php', true],
    'App\\Controller\\PartenaireController:newPartenaire' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UserController:newUser' => ['privates', '.service_locator.k22NER8', 'get_ServiceLocator_K22NER8Service.php', true],
], [
    'App\\Controller\\CompteController::alimenterCompte' => '?',
    'App\\Controller\\DepotController::depot' => '?',
    'App\\Controller\\PartenaireController::newPartenaire' => '?',
    'App\\Controller\\UserController::newUser' => '?',
    'App\\Controller\\CompteController:alimenterCompte' => '?',
    'App\\Controller\\DepotController:depot' => '?',
    'App\\Controller\\PartenaireController:newPartenaire' => '?',
    'App\\Controller\\UserController:newUser' => '?',
]);
