<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZdJT3DO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZdJT3DO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZdJT3DO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZdJT3DO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZdJT3DO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZdJT3DO',
    'container.build_id' => '7e643c71',
    'container.build_time' => 1564502331,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZdJT3DO');
