<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerThPqcvn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerThPqcvn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerThPqcvn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerThPqcvn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerThPqcvn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ThPqcvn',
    'container.build_id' => 'de38e3ac',
    'container.build_time' => 1564498929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerThPqcvn');
